import { JsonValue } from "type-fest";

export type Product = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  description: string | null;
  code: string | null;
  externalCode: string | null;
  archived: boolean | null;
  pathName: string | null;
  vatEnabled: boolean | null;
  useParentVat: boolean | null;
  images: JsonValue;
  minPrice: number | null;
  buyPrice: number | null;
  barcodes: JsonValue;
  attributes: JsonValue;
  article: string | null;
  weight: number | null;
  volume: number | null;
  meta: JsonValue;
  start: Date | null;
  end: Date | null;
  day: string | null;
  price: number | null;
  accountId: string | null;
  shared: boolean | null;
  updated: Date | null;
  name: string | null;
  effectiveVat: number | null;
  effectiveVatEnabled: boolean | null;
  vat: number | null;
  salePrices: JsonValue;
};
