import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

export type ProductWhereInput = {
  id?: StringFilter;
  description?: StringNullableFilter;
  code?: StringNullableFilter;
  externalCode?: StringNullableFilter;
  archived?: BooleanNullableFilter;
  pathName?: StringNullableFilter;
  vatEnabled?: BooleanNullableFilter;
  useParentVat?: BooleanNullableFilter;
  images?: JsonFilter;
  minPrice?: FloatNullableFilter;
  buyPrice?: FloatNullableFilter;
  barcodes?: JsonFilter;
  attributes?: JsonFilter;
  article?: StringNullableFilter;
  weight?: FloatNullableFilter;
  volume?: FloatNullableFilter;
  meta?: JsonFilter;
  start?: DateTimeNullableFilter;
  end?: DateTimeNullableFilter;
  day?: StringNullableFilter;
  price?: FloatNullableFilter;
  accountId?: StringNullableFilter;
  shared?: BooleanNullableFilter;
  updated?: DateTimeNullableFilter;
  name?: StringNullableFilter;
  effectiveVat?: IntNullableFilter;
  effectiveVatEnabled?: BooleanNullableFilter;
  vat?: IntNullableFilter;
  salePrices?: JsonFilter;
};
